config/routes.rb
Rails.application.routes.draw do
  root to: "vehicles#index"
  resources :vehicles, only: %i[index show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body_color.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: body_colors
#
#  id         :bigint           not null, primary key
#  exterior   :string
#  interior   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BodyColor < ApplicationRecord
  # validations
  validates :interior, :exterior, presence: true

  # relationship
  has_many :model_features, dependent: :destroy
end

app/models/model_feature.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: model_features
#
#  id            :bigint           not null, primary key
#  body_type     :integer
#  cylinders     :integer
#  displacement  :float
#  manufacturer  :string
#  model         :string
#  series        :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  body_color_id :bigint
#
# Indexes
#
#  index_model_features_on_body_color_id  (body_color_id)
#  index_model_features_on_body_type      (body_type)
#
# Foreign Keys
#
#  fk_rails_...  (body_color_id => body_colors.id)
#

class ModelFeature < ApplicationRecord
  enum body_type: {
    sedan: 0, suv: 1, convertible: 2, wagon_hatchback: 3, pickup: 4,
    crossover_utility_vehicle: 5, van: 6, coupe: 7, minivan: 8, wagon: 9
  }

  # validations
  validates :manufacturer, :body_type, :model, :series, presence: true

  # relationship
  has_many :vehicles, dependent: :destroy

  belongs_to :body_color
end

app/models/vehicle.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: vehicles
#
#  id               :bigint           not null, primary key
#  grade            :float
#  mileage          :integer
#  price            :decimal(10, 2)
#  stock            :integer
#  vin              :string
#  year             :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  model_feature_id :bigint
#
# Indexes
#
#  index_vehicles_on_mileage           (mileage)
#  index_vehicles_on_model_feature_id  (model_feature_id)
#  index_vehicles_on_price             (price)
#  index_vehicles_on_year              (year)
#
# Foreign Keys
#
#  fk_rails_...  (model_feature_id => model_features.id)
#

class Vehicle < ApplicationRecord
  # validation
  validates :mileage, :grade, :price, :vin, :year, presence: true

  # relationship
  belongs_to :model_feature
  has_one :body_color, through: :model_feature

  # delegations
  delegate :model, :manufacturer, :series, :body_type, :cylinders,
           :displacement, to: :model_feature
  delegate :interior, :exterior, to: :body_color
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/vehicles_controller.rb
# frozen_string_literal: true

class VehiclesController < ApplicationController
  def index
    @search = Vehicle.ransack(params[:q])
    @vehicles = @search
      .result
      .includes(:model_feature, :body_color)
      .page params[:page]
  end

  def show
    @vehicle = Vehicle.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/vehicles_helper.rb
# frozen_string_literal: true

module VehiclesHelper
  def interior_color_for_select
    BodyColor.distinct(:interior).pluck(:interior).sort
  end

  def exterior_color_for_select
    BodyColor.distinct(:interior).pluck(:exterior).sort
  end

  def body_type_for_select
    ModelFeature.body_types.map { |type, value| [type.humanize, value] }
  end
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Car Shop"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="/") Car Shop

    .container
      .row.min-row-container
        .col-lg-12
          = bootstrap_flash
          = yield
    %footer
      .container
        %p.text-muted &copy; Company 2020

app/views/vehicles/_search_form.html.haml
= search_form_for @search, url: vehicles_url, method: :get, class: 'form-horizontal' do |f|
  .form-group
    = f.label :mileage, class: 'control-label col-lg-2'
    .col-lg-10
      .col-lg-5
        = f.text_field :mileage_gteq, class: 'form-control', placeholder: 'Mileage greater than'
      .col-lg-5
        = f.text_field :mileage_lteq, class: 'form-control', placeholder: 'Mileage less than'
  .form-group
    = f.label :price, class: 'control-label col-lg-2'
    .col-lg-10
      .col-lg-5
        = f.text_field :price_gteq, class: 'form-control', placeholder: 'Price greater than'
      .col-lg-5
        = f.text_field :price_lteq, class: 'form-control', placeholder: 'Price less than'

  .form-group
    = f.label :color, class: 'control-label col-lg-2'
    .col-lg-10
      .col-lg-5
        = f.select :body_color_interior_eq, interior_color_for_select, { prompt: 'Choose interior', include_blank: true }, { class: 'form-control' }
      .col-lg-5
        = f.select :body_color_exterior_eq, exterior_color_for_select, { prompt: 'Choose exterior', include_blank: true }, { class: 'form-control' }

  .form-group
    = f.label :body_type, class: 'control-label col-lg-2'
    .col-lg-10
      .col-lg-5
        = f.select :model_feature_body_type_eq, body_type_for_select, { prompt: 'Choose body', include_blank: true }, { class: 'form-control' }

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit nil, class: 'btn btn-primary margin-lf-15'

app/views/vehicles/index.html.haml
- model_class = Vehicle
.page-header
  %h3=t '.title', :default => model_class.model_name.human.pluralize.titleize

= render partial: 'search_form'

= paginate @vehicles, theme: 'twitter-bootstrap-4'

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:vin)
      %th= model_class.human_attribute_name(:grade)
      %th= model_class.human_attribute_name(:price)
      %th= model_class.human_attribute_name(:year)
      %th= model_class.human_attribute_name(:mileage)
      %th= model_class.human_attribute_name(:manufacturer)
      %th= model_class.human_attribute_name(:model)
      %th= model_class.human_attribute_name(:series)
      %th= model_class.human_attribute_name(:body_type)
      %th= model_class.human_attribute_name(:interior)
      %th= model_class.human_attribute_name(:exterior)
  %tbody
    - @vehicles.each do |vehicle|
      %tr
        %td= link_to vehicle.id, vehicle_path(vehicle)
        %td= vehicle.vin
        %td= vehicle.grade
        %td= vehicle.price
        %td= vehicle.year
        %td= vehicle.mileage
        %td= vehicle.manufacturer
        %td= vehicle.model
        %td= vehicle.series
        %td= vehicle.body_type.humanize
        %td= vehicle.interior
        %td= vehicle.exterior

app/views/vehicles/show.html.haml
- model_class = Vehicle
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:vin) + ':'
  = @vehicle.vin
%p
  %strong= model_class.human_attribute_name(:grade) + ':'
  = @vehicle.grade
%p
  %strong= model_class.human_attribute_name(:stock) + ':'
  = @vehicle.stock
%p
  %strong= model_class.human_attribute_name(:price) + ':'
  = @vehicle.price
%p
  %strong= model_class.human_attribute_name(:year) + ':'
  = @vehicle.year
%p
  %strong= model_class.human_attribute_name(:mileage) + ':'
  = @vehicle.mileage
%p
  %strong= model_class.human_attribute_name(:manufacturer) + ':'
  = @vehicle.manufacturer
%p
  %strong= model_class.human_attribute_name(:model) + ':'
  = @vehicle.model
%p
  %strong= model_class.human_attribute_name(:series) + ':'
  = @vehicle.series
%p
  %strong= model_class.human_attribute_name(:cylinders) + ':'
  = @vehicle.cylinders
%p
  %strong= model_class.human_attribute_name(:displacement) + ':'
  = @vehicle.displacement
%p
  %strong= model_class.human_attribute_name(:body_type) + ':'
  = @vehicle.body_type.humanize
%p
  %strong= model_class.human_attribute_name(:interior) + ':'
  = @vehicle.interior
%p
  %strong= model_class.human_attribute_name(:exterior) + ':'
  = @vehicle.exterior

= link_to t('.back', :default => t("helpers.links.back")), vehicles_path, :class => 'btn btn-default'